### ISSUE TITLE
Module not Showing

### ISSUE THREAD

**Issue by nsprawling** [dsouzadrian/MMM-CricketScores#1]
I may well be missing something, but this doesn't seem to be working for me; I've installed the module and added it to my config:
![Screenshot 2022-07-08 130805](https://user-images.githubusercontent.com/73202904/177989193-86d2f3f9-9485-4ab7-ada0-e575026a322d.png)

I can see it calling the api, through the dash in RapidAPI, the response is good, but the module never displays.

**Comment by dsouzadrian** [comment]
Would you be able to attach Magic Mirror log files. 
Do you get a footer for the module showing "Last Updated: " and "Number of live matches" ?

**Comment by nsprawling** [comment]
Thanks for the quick response but I think I've solved it; the module just wasn't fitting into the display area below the forecast & clock.
